apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: revenexx-go
  title: Revenexx Go
  description: "Revenexx Go SDK for server-side applications."
  annotations:
    github.com/project-slug: revenexx-sdks/go
    backstage.io/techdocs-ref: url:https://github.com/revenexx-sdks/go/tree/main/
  links:
    - url: https://github.com/revenexx-sdks/go
      title: GitHub Repository
      icon: github
spec:
  type: library
  lifecycle: production
  owner: group:default/developer-experience
  system: revenue-cloud
