package models

import (
    "encoding/json"
    "errors"
)

// AssetFamilies model.
type AssetFamilies struct {
    // The asset family's stable identifier — a class of media with one shared
    // shape. Unique per tenant.
    Code string `json:"code"`
    // When the row was created. Server-set — it is not part of any request
    // body.
    CreatedAt string `json:"created_at"`
    // The row's own id, generated by the database. A client never sends one; it
    // reads one back and uses it in the path of every later call.
    Id string `json:"id"`
    // What the asset family is called, per language tag.
    Labels interface{} `json:"labels"`
    // How a file of this family is named, so an import can bind a file to a
    // product without a mapping table. `source` is the product value the file
    // name is built from, `pattern` how it is assembled, `allowed_extensions`
    // what may be uploaded.
    NamingConvention interface{} `json:"naming_convention"`
    // When the row was last written. Server-set — it is not part of any request
    // body.
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model AssetFamilies) New(data []byte) *AssetFamilies {
    model.data = data
    return &model
}

func (model *AssetFamilies) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}