package models

import (
    "encoding/json"
    "errors"
)

// AttributeGroups model.
type AttributeGroups struct {
    // The group's stable identifier, and the value an `AttributeField` carries as
    // its `group` — a SECTION of the product form, not a label. Unique per
    // tenant and the key an import joins on.
    Code string `json:"code"`
    // When the row was created. Server-set — it is not part of any request
    // body.
    CreatedAt string `json:"created_at"`
    // The row's own id, generated by the database. A client never sends one; it
    // reads one back and uses it in the path of every later call.
    Id string `json:"id"`
    // The section heading a person sees, keyed by language tag. The code is never
    // shown to an operator; a tag nobody translated falls back to the next filled
    // one, then to English.
    Labels interface{} `json:"labels"`
    // Where this section sits in a form, ascending. Sections that tie keep the
    // order the database returns them in.
    Position int `json:"position"`
    // When the row was last written. Server-set — it is not part of any request
    // body.
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model AttributeGroups) New(data []byte) *AttributeGroups {
    model.data = data
    return &model
}

func (model *AttributeGroups) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}