package models

import (
    "encoding/json"
    "errors"
)

// AttributeOptions model.
type AttributeOptions struct {
    // The select / multi-select attribute these are the permitted values of.
    // Deleting the attribute deletes its options with it.
    AttributeId string `json:"attribute_id"`
    // The value actually STORED in a record's `attribute_values` when this option
    // is picked — never the label. Unique within the attribute.
    Code string `json:"code"`
    // When the row was created. Server-set — it is not part of any request
    // body.
    CreatedAt string `json:"created_at"`
    // The row's own id, generated by the database. A client never sends one; it
    // reads one back and uses it in the path of every later call.
    Id string `json:"id"`
    // What the option is called, per language tag. Two tenants may label the same
    // code differently; only the code is ever written into a record.
    Labels interface{} `json:"labels"`
    // Order in the dropdown, ascending. Options that tie keep the order the
    // database returns them in, so give every option a position if the order
    // matters.
    Position int `json:"position"`
    // A colour or texture chip for the picker. Null for an option that is not
    // visual.
    Swatch interface{} `json:"swatch"`

    // Used by Decode() method
    data []byte
}

func (model AttributeOptions) New(data []byte) *AttributeOptions {
    model.data = data
    return &model
}

func (model *AttributeOptions) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}