package models

import (
    "encoding/json"
    "errors"
)

// Categories model.
type Categories struct {
    // The category's stable identifier — what an import and a storefront join
    // on, and what survives a rename of the label. Unique per tenant.
    Code string `json:"code"`
    // When the row was created. Server-set — it is not part of any request
    // body.
    CreatedAt string `json:"created_at"`
    // The row's own id, generated by the database. A client never sends one; it
    // reads one back and uses it in the path of every later call.
    Id string `json:"id"`
    // The category name a person sees, per language tag. The catalog reads by
    // name, not by code — a locale left blank falls back to the next filled
    // one.
    Labels interface{} `json:"labels"`
    // The category this one hangs under. Null is a root of the tree. Deleting a
    // parent lifts its children to the root rather than deleting them, so a
    // mis-click never takes a subtree with it.
    ParentId string `json:"parent_id"`
    // A materialized position in the tree, kept for importers that carry one
    // (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads
    // it — `parent_id` is the structure this app navigates.
    Path string `json:"path"`
    // Order among the siblings under the same parent, ascending.
    Position int `json:"position"`
    // How the conditions combine: 'all' ANDs them (the default), 'any' ORs them.
    // It is a column of its own rather than a key of `rules` because the compiler
    // reads the two separately.
    RuleMatch string `json:"rule_match"`
    // The selector that makes this a RULE-DRIVEN category. Null means
    // hand-picked. Matching products are MATERIALIZED as `product_categories`
    // rows with source `rule`, next to the hand-picked ones a recompute never
    // touches; `POST /products/categories/{category_id}/rules/preview` dry-runs
    // this exact document before it is stored. Conditions address the `common`
    // bucket of a product's values — a value held per locale or per channel has
    // no single answer for a rule to test.
    Rules interface{} `json:"rules"`
    // When the rule last ran TO COMPLETION and its memberships were synced. Null
    // means no pass has ever finished — a recompute is chunked, so a
    // half-finished pass leaves this untouched.
    RulesComputedAt string `json:"rules_computed_at"`
    // When the row was last written. Server-set — it is not part of any request
    // body.
    UpdatedAt string `json:"updated_at"`
    // Whatever this catalog keeps on a category beyond the model — the keys
    // belong to the tenant, not to this app, and nothing here reads them.
    Values interface{} `json:"values"`

    // Used by Decode() method
    data []byte
}

func (model Categories) New(data []byte) *Categories {
    model.data = data
    return &model
}

func (model *Categories) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}