package models

import (
    "encoding/json"
    "errors"
)

// FamilyVariants model.
type FamilyVariants struct {
    // The attribute codes a product model splits its variants on. Two shapes are
    // in the wild and both are read: a bare list of codes, or one entry per
    // level, outermost first — `[{"level": 1, "axes": ["colour"]}, {"level": 2,
    // "axes": ["size"]}]`. An attribute named here is READ-ONLY on the model and
    // set on each variant, which is what `AttributeField.readonly_reason`
    // reports.
    Axes interface{} `json:"axes"`
    // The variant structure's stable identifier — how this family splits, not
    // which product it splits. Unique per tenant.
    Code string `json:"code"`
    // When the row was created. Server-set — it is not part of any request
    // body.
    CreatedAt string `json:"created_at"`
    // The family this variant structure belongs to. A family may carry several,
    // and a product names the one it follows through `family_variant_id`.
    FamilyId string `json:"family_id"`
    // The row's own id, generated by the database. A client never sends one; it
    // reads one back and uses it in the path of every later call.
    Id string `json:"id"`
    // What the variant structure is called, per language tag.
    Labels interface{} `json:"labels"`
    // When the row was last written. Server-set — it is not part of any request
    // body.
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model FamilyVariants) New(data []byte) *FamilyVariants {
    model.data = data
    return &model
}

func (model *FamilyVariants) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}