package models

import (
    "encoding/json"
    "errors"
)

// Families model.
type Families struct {
    // The family's stable identifier — which set of attributes a product of
    // this family HAS. Unique per tenant, and the value `GET
    // /products/attribute-schema?family_code=` resolves.
    Code string `json:"code"`
    // When the row was created. Server-set — it is not part of any request
    // body.
    CreatedAt string `json:"created_at"`
    // The row's own id, generated by the database. A client never sends one; it
    // reads one back and uses it in the path of every later call.
    Id string `json:"id"`
    // Which attribute code carries the product's main image — the one a grid
    // thumbnail and a picker read.
    ImageAttribute string `json:"image_attribute"`
    // Which attribute CODE carries the display name of a product in this family.
    // A product's name is an attribute, not a column, and which attribute it is,
    // is per family. Null falls back to the `default_label_attribute` setting and
    // then to the conventional `name`.
    LabelAttribute string `json:"label_attribute"`
    // What the family is called, per language tag — the name an operator picks
    // from, while the code is what everything else joins on.
    Labels interface{} `json:"labels"`
    // When the row was last written. Server-set — it is not part of any request
    // body.
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model Families) New(data []byte) *Families {
    model.data = data
    return &model
}

func (model *Families) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}