package models

import (
    "encoding/json"
    "errors"
)

// Form model.
type Form struct {
    // When the form was first stored.
    CreatedAt string `json:"created_at"`
    // The form itself: a FormKit schema, held as a flat ARRAY of nodes (it
    // defaults to `[]`, never to an object) and rendered verbatim by the
    // storefront.
    // 
    // Read it as the field list. Every node carrying a non-empty `name` collects
    // one value and writes it into a submission's `data` under exactly that name
    // — the example below produces `{"company": …, "email": …, "message":
    // …}` — while `$el` content nodes and `$rxStep` step markers collect
    // nothing. Order is render order, and a `$rxStep` marker starts a new wizard
    // step.
    // 
    // See the `FormKitNode` schema for what a node may carry.
    Definition []FormKitNode `json:"definition"`
    // The form's own id, generated by the database. It is what a submission's
    // `form_id` points at and what the Cockpit and the storefront BFF hold once
    // they have resolved a form, so it outlives a rename of the slug.
    Id string `json:"id"`
    // Free-form metadata on the FORM, which this app neither reads nor writes:
    // yours to key however an integration needs, stored and returned verbatim.
    // (The metadata this app does write is on a SUBMISSION — see
    // `FormSubmissionMetadata`.)
    Metadata interface{} `json:"metadata"`
    // What this form is called in the Cockpit's form list. Operator-facing only
    // — the storefront never renders it, so renaming a form breaks no page.
    Name string `json:"name"`
    // Everything about a form that is not a field: what the storefront renders
    // around the inputs, what happens after a successful submit, and who is told
    // about it. Open jsonb, so an unknown key is stored and handed back rather
    // than refused — the keys below are the ones something actually READS, and
    // each says which reader that is. Null on a form nobody has configured, which
    // is not an error: every one of these has a fallback.
    Settings FormSettings `json:"settings"`
    // URL-safe identifier, unique per tenant. This is the name a storefront
    // resolves a form by (`GET /v1/forms?slug=contact&status=live&limit=1`), so
    // it is part of the page's contract: changing it changes which form a page
    // renders. Lower-case letters, digits and inner hyphens.
    Slug string `json:"slug"`
    // Lifecycle. `draft` while it is being built; `live` once the storefront may
    // render it — the cover BFF resolves live forms only, so a draft is a 404
    // on the storefront and never a broken page; `archived` for a form that is
    // kept for its submissions but no longer offered. Default 'draft'.
    Status string `json:"status"`
    // The tenant this row belongs to — the store slug, not an id. Set by the
    // platform from the authenticated context, never by a caller; a write that
    // carries it is ignored, and no request can read another tenant's rows by
    // sending a different one.
    TenantId string `json:"tenant_id"`
    // When the form was last written. This app stamps it on every PUT, so it is
    // the timestamp an editor sorts by.
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model Form) New(data []byte) *Form {
    model.data = data
    return &model
}

func (model *Form) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}