package models

import (
    "encoding/json"
    "errors"
)

// OrderListWithItems model.
type OrderListWithItems struct {
    // When the list was created.
    CreatedAt string `json:"created_at"`
    // The list, by id. Generated by the database and the only way to address it
    // — every /orderlists/{id} route takes this uuid.
    Id string `json:"id"`
    // Every position of the list, in `position` order. Returned inline because a
    // list without its positions is not a list — the nested routes exist to
    // CHANGE them, not to read them one page at a time.
    Items []OrderListItem `json:"items"`
    // What the list is FOR — the `code` of one of the tenant's own kinds (GET
    // /orderlists/kinds). Nothing in this app branches on it: it groups and
    // filters lists, it does not change how positions are stored or how a
    // conversion runs. A merchant may add their own (reagent lists, sample lists)
    // without a release of this app.
    Kind string `json:"kind"`
    // Free-form data the tenant keeps on the list — an ERP requisition number,
    // a department, whatever an integration needs to recognise the list again.
    // Never read by this app, and never merged: a write replaces the whole
    // document.
    Metadata interface{} `json:"metadata"`
    // What the buyer calls this list. Free text, at least one character, and not
    // unique: two contacts may both keep a "Weekly office supplies". It is also
    // the name a NEW cart gets when POST /orderlists/{id}/cart creates one.
    Name string `json:"name"`
    // The organization the sharing is scoped to. Null means the list can only
    // ever be the owner's own: `shared` is meaningless without it, because there
    // is no set of people to share with. It is also what the order conversion
    // hands the orders app as the buying organization.
    OrganizationId string `json:"organization_id"`
    // The contact who owns the list. Ownership IS the authorization here: a
    // caller the gateway resolved to a contact sees their own lists plus their
    // organization's shared ones, and may write only their own — unless
    // `shared_lists_editable` opens a shared list to the whole owning
    // organization. Set once at create; no route moves a list to another owner.
    OwnerId string `json:"owner_id"`
    // The owner's display name as it stood when the list was created — a
    // snapshot, so renaming the contact does not rewrite it. Carried so a shared
    // list can say whose it is without a call to the contacts app.
    OwnerName string `json:"owner_name"`
    // Dead column: what `shared` was called before the 2026-06-20 rename
    // (`public` is a reserved word in most SDK target languages). Nothing reads
    // or writes it, so it is `false` on every list written since; it is still
    // returned only because the additive provisioner never dropped the column.
    // Read `shared` — this field says nothing about who may see the list.
    Public bool `json:"public"`
    // Whether the OWNING ORGANIZATION may see this list. False — the default
    // — keeps it private to `owner_id`, and a foreign private list answers 404
    // rather than 403, so an outsider learns nothing from the difference. True
    // lets every contact of `organization_id` READ it, and write it only where
    // the tenant turned on the `shared_lists_editable` setting. A list with no
    // `organization_id` shares with nobody however this is set.
    Shared bool `json:"shared"`
    // The tenant this row belongs to, as a slug. Set by the platform, never by a
    // caller — it is the row-level security scope, not a field, and every row a
    // request can reach is inside it already.
    TenantId string `json:"tenant_id"`
    // When the list or ANY of its positions last changed — adding, updating or
    // removing a position touches the list — so this is the timestamp a
    // "recently used" sort should read. It is also the default sort of GET
    // /orderlists (`updated_at.desc`).
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model OrderListWithItems) New(data []byte) *OrderListWithItems {
    model.data = data
    return &model
}

func (model *OrderListWithItems) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}