package models

import (
    "encoding/json"
    "errors"
)

// OrderListKindRow model.
type OrderListKindRow struct {
    // What `lists.kind` stores. Lowercase, immutable once created — renaming it
    // would orphan every list that carries it, so a merchant who wants a
    // different code creates a new kind and moves the lists over.
    Code string `json:"code"`
    // When the kind was created — the install for a seeded one.
    CreatedAt string `json:"created_at"`
    // What this kind is FOR, in the tenant's own words — the sentence a select
    // shows underneath the title. `descriptions` carries the localized forms.
    // Same caveat as `title`: a kind seeded before 0.15.0 may hold a serialized
    // locale map here (PE-450).
    Description string `json:"description"`
    // Localized descriptions, keyed by language tag. Same fallback as `labels`:
    // `description` is what a reader gets when their tag is missing.
    Descriptions interface{} `json:"descriptions"`
    // The kind, by id. Generated by the database and what every
    // /orderlists/kinds/{id} route addresses — the `code` is the identity a
    // LIST carries, the id is the identity a route takes.
    Id string `json:"id"`
    // The kind a list created without one gets. Exactly one row carries it —
    // promoting a kind demotes the previous holder — and the market-scoped
    // `default_kind` setting still wins where a tenant set it.
    IsDefault bool `json:"is_default"`
    // Seeded on install rather than created by the merchant. It changes nothing
    // about what may be done to the row: a system kind is still renameable, still
    // retirable, and still deletable once no list carries it.
    IsSystem bool `json:"is_system"`
    // Localized titles, keyed by language tag. `title` is what a reader gets when
    // their tag is missing, so this only ever adds languages — it never
    // replaces the plain one.
    Labels interface{} `json:"labels"`
    // Where this kind sits in a select, ascending. Ties fall back to the code, so
    // the order is stable.
    Position int `json:"position"`
    // The tenant this row belongs to, as a slug. Set by the platform, never by a
    // caller — it is the row-level security scope, not a field, and every row a
    // request can reach is inside it already.
    TenantId string `json:"tenant_id"`
    // What a person reads, in the tenant's own words. `labels` carries the
    // localized forms. Kinds seeded before 0.15.0 hold a serialized locale map
    // here instead — the seed wrote its `{en, de}` map into this `text` column
    // and left `labels` null, and Postgres stores such a map as its JSON text
    // rather than refusing it (PE-450). Those rows are not repaired by the fix; a
    // repair is a data change.
    Title string `json:"title"`
    // Semantic badge colour. The client owns what each tone looks like; the kind
    // only says what the value MEANS.
    Tone string `json:"tone"`
    // When the kind was last written.
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model OrderListKindRow) New(data []byte) *OrderListKindRow {
    model.data = data
    return &model
}

func (model *OrderListKindRow) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}