package models

import (
    "encoding/json"
    "errors"
)

// ReferenceEntities model.
type ReferenceEntities struct {
    // The entity's stable identifier — a domain of records the catalog POINTS
    // AT instead of duplicating, so a brand is edited once and not on nine
    // thousand products. Unique per tenant.
    Code string `json:"code"`
    // When the row was created. Server-set — it is not part of any request
    // body.
    CreatedAt string `json:"created_at"`
    // The row's own id, generated by the database. A client never sends one; it
    // reads one back and uses it in the path of every later call.
    Id string `json:"id"`
    // A delivery path or URL for the entity's own icon. Cosmetic — nothing in
    // this app resolves it.
    Image string `json:"image"`
    // What the entity is called, per language tag — the heading over its record
    // list.
    Labels interface{} `json:"labels"`
    // When the row was last written. Server-set — it is not part of any request
    // body.
    UpdatedAt string `json:"updated_at"`

    // Used by Decode() method
    data []byte
}

func (model ReferenceEntities) New(data []byte) *ReferenceEntities {
    model.data = data
    return &model
}

func (model *ReferenceEntities) Decode(value interface{}) error {
    if len(model.data) <= 0 {
        return errors.New("method Decode() cannot be used on nested struct")
    }

    err := json.Unmarshal(model.data, value)
    if err != nil {
        return err
    }

    return nil
}